// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContadorActual():Promise<number>;

export function GetImpresoraActual():Promise<string>;

export function Imprimir(arg1:number):Promise<void>;

export function TestImpresora():Promise<void>;
