// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContadorActual() {
  return window['go']['main']['App']['GetContadorActual']();
}

export function GetImpresoraActual() {
  return window['go']['main']['App']['GetImpresoraActual']();
}

export function Imprimir(arg1) {
  return window['go']['main']['App']['Imprimir'](arg1);
}

export function TestImpresora() {
  return window['go']['main']['App']['TestImpresora']();
}
